<div id="mana_comment_progress" class="dialog message mana_comment_status" style="display:none">
 <div id="loading"> <img src="[% interface | html %]/[% theme | html %]/img/spinner-small.gif" alt="" /> A submeter o comentário </div>
</div>
<div id="mana_comment_success" class="dialog message mana_comment_status" style="display:none">
 O seu comentário foi submetido </div>
<div id="mana_comment_failed" class="dialog alert mana_comment_status" style="display:none">
 O seu comentário não foi submetido. Por favor tente de novo. </div>