<!-- installer-strings.inc -->
<script>
    var MSG_LETTERS_ONLY=(_("Por favor introduza apenas letras."));
    var MSG_PASSWORD_MISMATCH=(_("As palavras-passe inseridas não correspondem"));
    var MSG_ONE_ENROLLMENTPERIOD =(_("Por favor escolha um período de inscrição em meses OU por data."));
    var MSG_ONLY_ONE_ENROLLMENTPERIOD=(_("Por favor escolha apenas um período de inscrição."));
    var MSG_LETTERS_NUMBERS_ONLY=(_("Por favor introduza apenas letras ou números."));
</script>
<!-- / installer-strings.inc -->
