[% INCLUDE 'blocking_errors.inc' %]
<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-plus"></i> Novo <span class="caret"></span></button>
 <ul class="dropdown-menu">
 <li><a href="/cgi-bin/koha/patroncards/edit-batch.pl?op=new">Lote de cartões</a></li>
 <li><a href="/cgi-bin/koha/patroncards/image-manage.pl">Imagem</a></li>
 <li><a href="/cgi-bin/koha/patroncards/edit-layout.pl?op=new">Esquema</a></li>
 <li><a href="/cgi-bin/koha/patroncards/edit-template.pl?op=new">Modelo de cartão</a></li>
 <li><a href="/cgi-bin/koha/patroncards/edit-profile.pl?op=new">Perfil da impressora</a></li>
 </ul>
 </div>
 <div class="btn-group">
 <button class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-edit"></i> Gerir <span class="caret"></span></button>
 <ul class="dropdown-menu">
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">Lotes de cartões</a></li>
 <li><a href="/cgi-bin/koha/patroncards/image-manage.pl">Imagens</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">Esquemas</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">Modelos de cartão</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">Perfis de impressora</a></li>
 </ul>
 </div>
</div>
