<fieldset>
 <legend>Campos codificados</legend>
 <p>
 <label>Audiência</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Qualquer</option>
 <option value="aud:a">juvenil, geral</option>
 <option value="aud:b">pré-escolar (0-5)</option>
 <option value="aud:c">primária (5-8)</option>
 <option value="aud:d">infantil (9-14)</option>
 <option value="aud:e">jovem adulto</option>
 <option value="aud:k">adulto, público especializado</option>
 <option value="aud:m">adulto, Geral</option>
 <option value="aud:u">desconhecido</option>
 </select>
 </p>
 <p>
 <label>Apresentação física</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Qualquer</option>
 <option value="Material-type:r">impressão normal</option>
 <option value="Material-type:d">impressão larga</option>
 <option value="Material-type:e">formato de jornal</option>
 <option value="Material-type:f">Braille ou Moon script</option>
 <option value="Material-type:g">micro-impressão</option>
 <option value="Material-type:h">manuscrito</option>
 <option value="Material-type:i">multimédia</option>
 <option value="Material-type:j">mini-impressão</option>
 <option value="Material-type:s">recurso electrónico</option>
 <option value="Material-type:t">microforma</option>
 <option value="Material-type:z">outra forma de material</option>
 </select>
 </p>
 <p>
 <label>Género literário</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Qualquer</option>
 <option value="Literature-Code:a">ficção</option>
 <option value="Literature-Code:b">drama</option>
 <option value="Literature-Code:c">ensaios</option>
 <option value="Literature-Code:d">humor, sátira</option>
 <option value="Literature-Code:e">cartas</option>
 <option value="Literature-Code:f">contos</option>
 <option value="Literature-Code:g">poesia</option>
 <option value="Literature-Code:h">discursos, oratória</option>
 <option value="Literature-Code:i">libreto</option>
 <option value="Literature-Code:y">texto não literário</option>
 <option value="Literature-Code:z">formas múltiplas ou outras formas literárias</option>
 </select>
 </p>
 <p>
 <label>Biografia</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Biography-code:y">texto não biográfico</option>
 <option value="Biography-code:a">autobiografia</option>
 <option value="Biography-code:b">biografia individual</option>
 <option value="Biography-code:c">biografia colectiva</option>
 <option value="Biography-code:d">contém informação biográfica</option>
 </select>
 </p>
 <p>
 <label>Ilustração</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Illustration-Code:a">ilustrações</option>
 <option value="Illustration-Code:b">mapas</option>
 <option value="Illustration-Code:c">retratos</option>
 <option value="Illustration-Code:d">gráficos</option>
 <option value="Illustration-Code:e">planos</option>
 <option value="Illustration-Code:f">placas</option>
 <option value="Illustration-Code:g">música</option>
 <option value="Illustration-Code:h">fac-símiles</option>
 <option value="Illustration-Code:i">brasões de armas</option>
 <option value="Illustration-Code:j">tabelas genealógicas</option>
 <option value="Illustration-Code:k">formulários</option>
 <option value="Illustration-Code:l">amostras</option>
 <option value="Illustration-Code:m">registos sonoros</option>
 <option value="Illustration-Code:n">transparências</option>
 <option value="Illustration-Code:o">iluminuras</option>
 <option value="Illustration-Code:y">sem ilustrações</option>
 </select>
 </p>
 <p>
 <label>Conteúdo</label>
 <select name="limit" class="subtype">
 <option value="" >Qualquer</option>
 <option value="ctype:a" >bibliografia</option>
 <option value="ctype:b" >catálogo</option>
 <option value="ctype:c" >índice</option>
 <option value="ctype:d" >resumo</option>
 <option value="ctype:e" >dicionário</option>
 <option value="ctype:f" >enciclopédia</option>
 <option value="ctype:g" >directoria</option>
 <option value="ctype:h" >descrição do projecto</option>
 <option value="ctype:i" >estatísticas</option>
 <option value="ctype:j" >livro de texto programado</option>
 <option value="ctype:k" >patente</option>
 <option value="ctype:l" >norma</option>
 <option value="ctype:m" >dissertação ou tese</option>
 <option value="ctype:n" >leis e legislação</option>
 <option value="ctype:o" >tabela numérica</option>
 <option value="ctype:p" >relatório técnico</option>
 <option value="ctype:q" >questionário para exame</option>
 <option value="ctype:r" >ensaios literários/revisões</option>
 <option value="ctype:s" >tratados</option>
 <option value="ctype:t" >banda desenhada</option>
 <option value="ctype:v" >dissertação ou tese (revista)</option>
 <option value="ctype:w" >texto religioso</option>
 <option value="ctype:z" >outro</option>
 </select>
 </p>
 <p>
 <label>Tipos de vídeo</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Video-mt:a">imagem em movimento</option>
 <option value="Video-mt:b">projecção visual</option>
 <option value="Video-mt:c">registo vídeo</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Periódicos</legend><p>
 <p>
 <label>Tipo de periódico</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer tipo</option>
 <option value="Type-Of-Serial:a">Periódico</option>
 <option value="Type-Of-Serial:b">Coleção monográfica</option>
 <option value="Type-Of-Serial:c">Jornal</option>
 <option value="Type-Of-Serial:e">Folha-solta em atualização</option>
 <option value="Type-Of-Serial:f">Base de dados</option>
 <option value="Type-Of-Serial:g">Website em atualização</option>
 <option value="Type-Of-Serial:z">Outros</option>
 </select>
 </p>
 <p>
 <label>Periodicidade</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Frequency-code:a">Diário</option>
 <option value="Frequency-code:b">Bisemanal</option>
 <option value="Frequency-code:c">Semanal</option>
 <option value="Frequency-code:d">Bisemanal</option>
 <option value="Frequency-code:e">Bimensal</option>
 <option value="Frequency-code:f">Mensal</option>
 <option value="Frequency-code:g">Bimensal</option>
 <option value="Frequency-code:h">Trimestrais</option>
 <option value="Frequency-code:i">Três vezes por ano</option>
 <option value="Frequency-code:j">Semestral</option>
 <option value="Frequency-code:k">Anual</option>
 <option value="Frequency-code:l">Bienal</option>
 <option value="Frequency-code:m">Trienal</option>
 <option value="Frequency-code:n">Três vezes por semana</option>
 <option value="Frequency-code:o">Três vezes por mês</option>
 <option value="Frequency-code:y">Sem periodicidade</option>
 <option value="Frequency-code:u">Desconhecido</option>
 <option value="Frequency-code:z">Outros</option>
 </select>
 </p>
 <p>
 <label>Regularidade</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer regularidade</option>
 <option value="Regularity-code:a">regular</option>
 <option value="Regularity-code:b">irregular normalizado</option>
 <option value="Regularity-code:y">irregular</option>
 <option value="Regularity-code:u">desconhecido</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Imagem</legend>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Graphics-type:a">colagem</option>
 <option value="Graphics-type:b">desenho</option>
 <option value="Graphics-type:c">pintura</option>
 <option value="Graphics-type:d">reprodução fotomecânica</option>
 <option value="Graphics-type:e">negativo fotográfico</option>
 <option value="Graphics-type:f">fotocópia</option>
 <option value="Graphics-type:h">imagem</option>
 <option value="Graphics-type:i">impressão</option>
 <option value="Graphics-type:k">desenho técnico</option>
 <option value="Graphics-type:z">outro material gráfico não-projectável</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Graphics-support:a">tela</option>
 <option value="Graphics-support:b">cartolina</option>
 <option value="Graphics-support:c">cartão/placa de ilustração</option>
 <option value="Graphics-support:d">vidro</option>
 <option value="Graphics-support:j">gesso</option>
 <option value="Graphics-support:k">cartão prensado</option>
 <option value="Graphics-support:l">porcelana</option>
 <option value="Graphics-support:m">pedra</option>
 <option value="Graphics-support:n">madeira</option>
 <option value="Graphics-support:v">coleção mista</option>
 <option value="Graphics-support:e">sintéticos</option>
 <option value="Graphics-support:f">película</option>
 <option value="Graphics-support:g">têxtil</option>
 <option value="Graphics-support:h">metal</option>
 <option value="Graphics-support:i">papel</option>
 <option value="Graphics-support:z">outros</option>
 <option value="Graphics-support:u">desconhecido</option>
 </select>
</fieldset>
